import type { IconProps } from '@phosphor-icons/react';
import {
  ArrowClockwise,
  ArrowLeft,
  ArrowRight,
  Bell,
  Camera,
  CaretDown,
  CaretLeft,
  CaretRight,
  CalendarBlank,
  Check,
  CheckCircle,
  Circle,
  Clock,
  Coffee,
  Compass,
  Copy,
  Envelope,
  EnvelopeOpen,
  Eye,
  EyeSlash,
  Factory,
  Flag,
  Flame,
  Flask,
  Globe,
  GridFour,
  Heart,
  House,
  Leaf,
  Lightning,
  Lock,
  MagnifyingGlass,
  MagnifyingGlassMinus,
  MapPin,
  MapTrifold,
  Moon,
  NotePencil,
  Palette,
  PaperPlaneTilt,
  PawPrint,
  PencilSimple,
  Phone,
  Rocket,
  SealCheck,
  ShareNetwork,
  ShoppingCart,
  SignIn,
  SignOut,
  SlidersHorizontal,
  SortAscending,
  Sparkle,
  Star,
  Storefront,
  Sun,
  TrendUp,
  ThumbsUp,
  User,
  UsersThree,
  WarningCircle,
  WifiHigh,
  X,
  XCircle,
  Drop,
  Avocado, Bread, Cake, CaretUp, CaretUpDown,
  ChatCenteredText, CoffeeBean, Egg, Footprints, ForkKnife, GearSix,
  GrainsSlash, ImageSquare, Images, Info, InstagramLogo, Laptop, ListStar,
  Minus, Monitor, NavigationArrow, PersonSimpleWalk, Plus, Polygon,
  ShoppingBag, Trash,
} from '@phosphor-icons/react';

export type PhosphorIconComponent = React.ComponentType<IconProps>;

export const MATERIAL_ICON_MAP: Record<string, PhosphorIconComponent> = {
  add_business: Storefront,
  apps: GridFour,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  auto_awesome: Sparkle,
  call: Phone,
  calendar_today: CalendarBlank,
  store: Storefront,
  cancel: XCircle,
  check: Check,
  check_circle: CheckCircle,
  chevron_left: CaretLeft,
  chevron_right: CaretRight,
  circle: Circle,
  close: X,
  coffee: Coffee,
  coffee_maker: Coffee,
  content_copy: Copy,
  deck: Sun,
  eco: Leaf,
  edit: PencilSimple,
  edit_note: NotePencil,
  edit_square: NotePencil,
  energy: Lightning,
  error: WarningCircle,
  expand_more: CaretDown,
  expand_less: CaretUp,
  explore: Compass,
  favorite: Heart,
  flag: Flag,
  grid_view: GridFour,
  groups: UsersThree,
  language: Globe,
  light_mode: Sun,
  local_cafe: Coffee,
  local_fire_department: Flame,
  location_on: MapPin,
  lock: Lock,
  login: SignIn,
  logout: SignOut,
  mail: Envelope,
  mark_email_read: EnvelopeOpen,
  notifications: Bell,
  palette: Palette,
  person: User,
  pets: PawPrint,
  photo_camera: Camera,
  pin_drop: MapPin,
  precision_manufacturing: Factory,
  public: Globe,
  rate_review: ChatCenteredText,
  refresh: ArrowClockwise,
  rocket_launch: Rocket,
  schedule: Clock,
  science: Flask,
  search: MagnifyingGlass,
  search_off: MagnifyingGlassMinus,
  send: PaperPlaneTilt,
  settings: GearSix,
  share: ShareNetwork,
  shopping_cart_checkout: ShoppingCart,
  star: Star,
  swap_vert: SortAscending,
  tool: GearSix,
  thumb_up: ThumbsUp,
  trending_up: TrendUp,
  tune: SlidersHorizontal,
  verified: SealCheck,
  visibility: Eye,
  visibility_off: EyeSlash,
  warning: WarningCircle,
  water_drop: Drop,
  wifi: WifiHigh,
  dark_mode: Moon,
  map: MapTrifold,
  home: House,
  info: Info,
  checkin: MapPin,
  'magnifying-glass': MagnifyingGlass,
  'map-trifold': MapTrifold,
  user: User,
  'gear-six': GearSix,
  'map-pin': MapPin,
  'navigation-arrow': NavigationArrow,
  polygon: Polygon,
  plus: Plus,
  minus: Minus,
  'arrow-left': ArrowLeft,
  'caret-left': CaretLeft,
  'caret-right': CaretRight,
  'caret-up': CaretUp,
  'caret-down': CaretDown,
  'caret-up-down': CaretUpDown,
  x: X,
  heart: Heart,
  'coffee-bean': CoffeeBean,
  factory: Factory,
  'sliders-horizontal': SlidersHorizontal,
  'person-simple-walk': PersonSimpleWalk,
  clock: Clock,
  'check-circle': CheckCircle,
  'chat-centered-text': ChatCenteredText,
  'note-pencil': NotePencil,
  'pencil-simple': PencilSimple,
  'share-network': ShareNetwork,
  copy: Copy,
  'thumbs-up': ThumbsUp,
  'calendar-blank': CalendarBlank,
  sparkle: Sparkle,
  'fork-knife': ForkKnife,
  'image-square': ImageSquare,
  envelope: Envelope,
  eye: Eye,
  'eye-slash': EyeSlash,
  phone: Phone,
  'instagram-logo': InstagramLogo,
  globe: Globe,
  'sign-out': SignOut,
  camera: Camera,
  images: Images,
  trash: Trash,
  'warning-circle': WarningCircle,
  moon: Moon,
  sun: Sun,
  monitor: Monitor,
  'list-star': ListStar,
};

export const SHOP_CHANGE_ICONS: Record<string, string> = {
  Description: 'note-pencil', Contacts: 'envelope', Photos: 'image-square',
  Tags: 'sparkle', Roasters: 'coffee-bean', Equipment: 'gear-six',
  BrewMethods: 'coffee', Menu: 'fork-knife',
};

export const SHOP_TAG_ICONS: Record<string, PhosphorIconComponent> = {
  roastery: Factory, 'beans-for-sale': ShoppingBag, decaf: CoffeeBean, to_go: Footprints,
  'plant-based-milk': Leaf, 'plan-based-milk': Leaf, laptop_friendly: Laptop,
  'outside-seating': Sun, breakfasts: Egg, bakery: Bread, confectionery: Cake,
  pet_friendly: PawPrint, vegan: Avocado, 'gluten-free': GrainsSlash,
};

const BREW_METHOD_IMAGES: Record<string, string> = {
  aeropress: 'aeropress', 'аэропресс': 'aeropress',
  batchbrew: 'batch-brew', 'батчбрю': 'batch-brew',
  cezve: 'cezve', 'cezve(turkishcoffee)': 'cezve', 'джезва': 'cezve', 'турка': 'cezve',
  chemex: 'chemex', 'кемекс': 'chemex',
  coldbrew: 'cold-brew', 'колдбрю': 'cold-brew',
  espresso: 'espresso', 'эспрессо': 'espresso', v60: 'v60', hariov60: 'v60',
};

export function getBrewMethodImage(name: string): string | undefined {
  const key = name.trim().toLowerCase().replace(/[\s_-]+/g, '');
  const file = Object.hasOwn(BREW_METHOD_IMAGES, key) ? BREW_METHOD_IMAGES[key] : undefined;
  return file ? `/icons/brew-methods/${file}.svg` : undefined;
}

export type MaterialIconName = keyof typeof MATERIAL_ICON_MAP;

export function isMaterialIconName(name: string): name is MaterialIconName {
  return Object.hasOwn(MATERIAL_ICON_MAP, name);
}
